# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55bfc5ce8ba2c6317c884434e788316ed5b1ab5163c9608b70b3f3f74929ebdbf5008bf6854ce4e2624b6706e83fbe34426dc4a51c866fd97103d12c5d777d12

test:
  secret_key_base: cde7ce777c745d7bda148cbe88aa6b09e38ec1446dd1be86fd2509c88ced15f8aabc543cf497e345c9bdd56ef1b242f18cfb02efb3b3a1f851bb71982b03b5e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
